module:
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  cohesion: 0
  cohesion_base_styles: 0
  cohesion_custom_styles: 0
  cohesion_elements: 0
  cohesion_style_helpers: 0
  cohesion_sync: 0
  cohesion_templates: 0
  cohesion_website_settings: 0
  color: 0
  comment: 0
  config: 0
  contextual: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  image: 0
  imce: 0
  link: 0
  menu_link_content: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  rest: 0
  serialization: 0
  settings_tray: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  tome: 0
  tome_base: 0
  tome_static: 0
  tome_sync: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_ui: 0
  views: 10
  standard: 1000
theme:
  bartik: 0
  seven: 0
  stable: 0
  cohesion_theme: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
